import checkProjectBit from './econ/checkProjectBit.js';
import cityCost from './econ/cityCost.js';
import { crime, disease, pollution, pollutionIndex } from './econ/cityEffects.js';
import cityIncome from './econ/cityIncome.js';
import foodConsumption from './econ/foodConsumption.js';
import foodProduction from './econ/foodProduction.js';
import infraCost from './econ/infraCost.js';
import landCost from './econ/landCost.js';
import projectCost from './econ/projectCost.js';
import researchCost from './econ/researchCost.js';
import resourceProduction from './econ/resourceProduction.js';
import accurateRounding from './other/accurateRounding.js';
import getDaysBetween from './other/getDaysBetween.js';
import getPercentage from './other/getPercentage.js';
import activeWars from './war/activeWars.js';
import allianceMMR from './war/allianceMMR.js';
import allianceTiering from './war/allianceTiering.js';
import { airBattle, groundBattle, seaBattle } from './war/battleSimulations.js';
import espionageOdds from './war/espionageOdds.js';
import nationMMR from './war/nationMMR.js';
import sphereTiering from './war/sphereTiering.js';
import spyRange from './war/spyRange.js';
import warRange from './war/warRange.js';

export default class PnwKitUtils {
    getPercentage = getPercentage;
    accurateRounding = accurateRounding;
    infraCost = infraCost;
    landCost = landCost;
    cityCost = cityCost;
    foodProduciton = foodProduction;
    foodConsumption = foodConsumption;
    resourceProduction = resourceProduction;
    warRange = warRange;
    spyRange = spyRange;
    espionageOdds = espionageOdds;
    groundBattle = groundBattle;
    airBattle = airBattle;
    seaBattle = seaBattle;
    pollution = pollution;
    pollutionIndex = pollutionIndex;
    crime = crime;
    disease = disease;
    projectCost = projectCost;
    cityIncome = cityIncome;
    allianceMMR = allianceMMR;
    nationMMR = nationMMR;
    sphereTiering = sphereTiering;
    activeWars = activeWars;
    allianceTiering = allianceTiering;
    checkProjectBit = checkProjectBit;
    getDaysBetween = getDaysBetween;
    researchCost = researchCost;
}