import activityStatQuery from "./queries/activityStatQuery.js";
import allianceQuery from "./queries/allianceQuery.js";
import apiKeyDetailsQuery from "./queries/apiKeyDetailsQuery.js";
import bankRecordsQuery from "./queries/bankRecQuery.js";
import baseballGameQuery from "./queries/baseballGameQuery.js";
import baseballPlayerQuery from "./queries/baseballPlayerQuery.js";
import baseballTeamQuery from "./queries/baseballTeamQuery.js";
import bountyQuery from "./queries/bountyQuery.js";
import cityQuery from "./queries/cityQuery.js";
import colorQuery from "./queries/colorQuery.js";
import embargoQuery from "./queries/embaroQuery.js";
import gameInfoQuery from "./queries/gameInfoQuery.js";
import nationQuery from "./queries/nationQuery.js";
import resourceStatQuery from "./queries/resourceStatQuery.js";
import tradePricesQuery from "./queries/tradePricesQuery.js";
import tradeQuery from "./queries/tradeQuery.js";
import treasureQuery from "./queries/treasureQuery.js";
import treasureTradeQuery from "./queries/treasureTradeQuery.js";
import warAttackQuery from "./queries/warAttackQuery.js";
import warQuery from "./queries/warQuery.js";
import topTradeInfoQuery from "./queries/topTradeInfoQuery.js";
import treatyQuery from "./queries/treatyQuery.js";
import alliancePositionSubscription from "./subscriptions/alliancePositionSubscription.js";
import allianceSubscription from "./subscriptions/allianceSubscription.js";
import bankRecSubscription from "./subscriptions/bankRecSubscription.js";
import baseballGameSubscription from "./subscriptions/baseballGameSubscription.js";
import baseballTeamSubscription from "./subscriptions/baseballTeamSubscription.js";
import bountySubscription from "./subscriptions/bountySubsciption.js";
import citySubscription from "./subscriptions/citySubscription.js";
import embargoSubscription from "./subscriptions/embargoSubsciptions.js";
import nationSubscription from "./subscriptions/nationSubscription.js";
import taxBracketSubscription from "./subscriptions/taxBracketSubscription.js";
import tradeSubscription from "./subscriptions/tradeSubscription.js";
import treasureSubscription from "./subscriptions/treasureTradeSubscription.js";
import treatySubscription from "./subscriptions/treatySubscription.js";
import warAttackSubscription from "./subscriptions/warAttackSubscription.js";
import warSubscription from "./subscriptions/warSubscription.js";
import bankDepositMutation from "./mutations/bankDepositMutation.js";
import bankWithdrawMutation from "./mutations/bankWithdrawMutation.js";
import approveTreatyMutation from "./mutations/approveTreatyMutation.js";
import assignTaxBracketMutation from "./mutations/assignTaxBracketMutation.js";
import cancelTreatyMutation from "./mutations/cancelTreatyMutation.js";
import createTaxBracketMutation from "./mutations/createTaxBracketMutation.js";
import deleteTaxBracketMutation from "./mutations/deleteTaxBracketMutation.js";
import editTaxBracketMutation from "./mutations/editTaxBracketMutation.js";
import proposeTreatyMutation from "./mutations/proposeTreatyMutation.js";
import sendMessage from "./v2/sendMessage.js";
import bannedNationQuery from "./queries/bannedNationQuery.js";
import nationResourceStatQuery from "./queries/nationResourceStatQuery.js";
import customQuery from "./queries/customQuery.js";
import acceptPersonalTradeMutation from "./mutations/acceptPersonalTradeMutation.js";
import declinePersonalTradeMutation from "./mutations/declinePersonalTradeMutation.js";
import assignAlliancePositionMutation from "./mutations/assignAlliancePositionMutation.js";
import editAlliancePositionMutation from "./mutations/editAlliancePositionMutation.js";
import deleteAlliancePositionMutation from "./mutations/deleteAlliancePositionMutation.js";
import createAlliancePositionMutation from "./mutations/createAlliancePositionMutation.js";
import subscriptionChannel from "./subscriptions/subscriptionChannel.js";
import bulletinQuery from "./queries/bulletinQuery.js";
import bulletinReplyQuery from "./queries/bulletinReplyQuery.js";


export default class PnwKitAPI {
    activityStatQuery = activityStatQuery;
    allianceQuery = allianceQuery;
    apiKeyDetailsQuery = apiKeyDetailsQuery;
    bankRecordsQuery = bankRecordsQuery;
    baseballGameQuery = baseballGameQuery;
    baseballPlayerQuery = baseballPlayerQuery;
    baseballTeamQuery = baseballTeamQuery;
    bountyQuery = bountyQuery;
    cityQuery = cityQuery;
    colorQuery = colorQuery;
    embargoQuery = embargoQuery;
    gameInfoQuery = gameInfoQuery;
    nationQuery = nationQuery;
    resourceStatQuery = resourceStatQuery;
    tradePricesQuery = tradePricesQuery;
    tradeQuery = tradeQuery;
    treasureQuery = treasureQuery;
    treasureTradeQuery = treasureTradeQuery;
    warAttackQuery = warAttackQuery;
    warQuery = warQuery;
    topTradeInfoQuery = topTradeInfoQuery;
    bannedNationQuery = bannedNationQuery;
    nationResourceStatQuery = nationResourceStatQuery;
    customQuery = customQuery;
    bulletinQuery = bulletinQuery;
    bulletinReplyQuery = bulletinReplyQuery;
    treatyQuery = treatyQuery;
    alliancePositionSubscription = alliancePositionSubscription;
    allianceSubscription = allianceSubscription;
    bankRecSubscription = bankRecSubscription;
    baseballGameSubscription = baseballGameSubscription;
    baseballTeamSubscription = baseballTeamSubscription;
    bountySubscription = bountySubscription;
    citySubscription = citySubscription;
    embargoSubscription = embargoSubscription;
    nationSubscription = nationSubscription;
    taxBracketSubscription = taxBracketSubscription;
    tradeSubscription = tradeSubscription;
    treasureSubscription = treasureSubscription;
    treatySubscription = treatySubscription;
    warAttackSubscription = warAttackSubscription;
    warSubscription = warSubscription;
    approveTreatyMutation = approveTreatyMutation;
    assignTaxBracketMutation = assignTaxBracketMutation;
    bankDepositMutation = bankDepositMutation;
    bankWithdrawMutation = bankWithdrawMutation;
    cancelTreatyMutation = cancelTreatyMutation;
    createTaxBracketMutation = createTaxBracketMutation;
    deleteTaxBracketMutation = deleteTaxBracketMutation;
    editTaxBracketMutation = editTaxBracketMutation;
    proposeTreatyMutation = proposeTreatyMutation;
    sendMessage = sendMessage;
    acceptPersonalTradeMutation = acceptPersonalTradeMutation;
    declinePersonalTradeMutation = declinePersonalTradeMutation;
    assignAlliancePositionMutation = assignAlliancePositionMutation;
    editAlliancePositionMutation = editAlliancePositionMutation;
    deleteAlliancePositionMutation = deleteAlliancePositionMutation;
    createAlliancePositionMutation = createAlliancePositionMutation;
    subscriptionChannel = subscriptionChannel;
}
